name:                DHI
version:             0.1.0.0
github:              "blueOkiris/DHI"
license:             GPL3
author:              "Dylan Turner"
maintainer:          "dylantdmt@gmail.com"
copyright:           "2020 Dylan Turner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/blueOkiris/DHI>

dependencies:
- base >= 4.7 && < 5
- Chart
- Chart-cairo
- matrix

library:
  source-dirs: src

executables:
  dhi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DHI
    
